[features]
seeds = false
skip-lint = false
[programs.localnet]
solcial = "9b78iHesNLGXKEULj9upDG5o6Eiu1f8A8WJ2egGukCaZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ducnh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
